"project_identifier" : "youtrackjetbrains"
"api_key_env" : CROWDIN_API_KEY
"base_path_env" : CROWDIN_BASE_PATH

"preserve_hierarchy": true

files: [
 {
  "source" : "/src/app/translations/youtrack-agile-chart-widget.pot",
  "dest": "/widgets/youtrack-agile-chart-widget/youtrack-agile-chart-widget.pot",
  "translation" : "/src/app/translations/youtrack-agile-chart-widget_%two_letters_code%.po",
 }
]
